### ISSUE TITLE
Feedback Request: AWS-09 Shared Responsibility Model

### ISSUE THREAD

**Issue by Rolfsijtema** [TechGrounds-Cloud8/cloud8-Rolfsijtema#26]
**Feedback Request[AWS-09 Shared Responsibility Model]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-Rolfsijtema/blob/71e1d3b878f229ea89814a9684dd3673c360166f/week5cloud8/AWS-09%20Shared%20Responsibility%20Model.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
the model itself is not purely for security actions.  i would reread the entire model a bit. i can help you with it. im not sure if you dont understand a few things or that you just worded it wrongly and i would not talk about azure inside the AWS, AWS has nothing todo with azure. I also miss info about CIS, you explain what it means in key terms but not what it does, bit confusing.

for example what do you mean with AWS is responsibly for security OF the cloud. because there is a difference between of and in the cloud.  AWS is also not responsible for the customer data. 

If needed i can explain this all later on but firstly i would just reread the model page on AWS

**Comment by sasudi90** [comment]
**Summary**
- Does the summary describe the subject matter fully? n, covers more than responsibilities on the security side alone
- Is the summary written in own words? y 
- Is there crucial information missing in the summary? n
- Is the description clear enough? y

**Key Terminology**
- Are there missing key terms? y
- Are the key terms explained well? n

**Sources**
- Are the sources mentioned? y
- Are the mentioned sources correct? n

**Excercise**
(Where applicable)
- Is the result correct? n
- Are the experienced problems and solutions described well? n
Why are u taking CIS into account?
